node{
  stage ('SCM Checkout'){
    
  git 'https://github.com/ashish22795/devopstest' 
  }
  stage ('Compile-Package'){
    def mvnHome = tool name: 'M3', type: 'maven'
    sh "${mvnHome}/bin/mvn clean package"
  }

}
